# Generated by Django 5.2.8 on 2025-11-16 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("system_modules", models.JSONField(default=list)),
                ("permissions", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="estado",
        ),
        migrations.AddField(
            model_name="usuario",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.grupo",
            ),
        ),
    ]
