"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from corsheaders.defaults import default_headers
from pathlib import Path
import os

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#


# initialize environment variables

env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

# Multi-Factor Authentication settings
MFA_ISSUER = "S360 ERP"




# Application definition

SHARED_APPS = [
    'django_prometheus',
    'django_tenants',
    'widget_tweaks',
    'django_user_agents',
    'cacheops',
    'rest_framework',
    'rest_framework.authtoken',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # swagger
    'drf_yasg',
    'core.homepage',
    'core.multicpy',
    'core.security',
    'core.user',


    'users',
    # 'cause user sales filtering logic
    'administration',
]

TENANT_APPS = [
    'django_prometheus',
    # important to handle tokens in tenants
    'rest_framework',
    'rest_framework.authtoken',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # swagger
    'drf_yasg',

    'core.billing',
    'core.dashboard',
    'core.login',
    'core.security',
    'core.network',
    'core.user',

    # own django apps
    'users',
    'administration',
    'servicios',
    'nomina',
    'comercial',
    'infraestructura',
    'mantenimientoope',
    'cobranza',
    'clientes',
    'operaciones',
    'inventario',
    'tecnico',

    'contabilidad',
    'webhooks',
    'televentas',
    'cartera',
    'customerexperience',
    'cronjobs',
    

]

# INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
INSTALLED_APPS = [
    'django_tenants', 'widget_tweaks', 'django_user_agents', 'cacheops', 'rest_framework', 'rest_framework.authtoken', 'django_cleanup.apps.CleanupConfig', 'django.contrib.staticfiles', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'core.homepage', 'core.multicpy', 'core.security', 'core.user', 'core.billing', 'core.dashboard', 'core.login', 'core.network',
    # 'django_crontab',
    # swagger
    'encrypted_model_fields',
    'drf_yasg',
    'users',
    'administration',
    'servicios',
    'nomina',
    'comercial',
    'infraestructura',
    'mantenimientoope',
    'cobranza',
    'clientes',
    'operaciones',
    'inventario',
    'tecnico',
    'contabilidad',
    'webhooks',
    'televentas',
    'cartera',
    'customerexperience',
    'cronjobs',
    
]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'core.multicpy.middleware.CustomTenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # #### CORS headers: before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',

    # ### Custom Middlewares
    'config.shared.middlewares.not_found_middleware.Custom404Middleware',
    'config.shared.middlewares.unauthorized_middleware.CustomUnauthorizedMiddleware',
    'config.shared.middlewares.front_version_middleware.FrontVersionMiddleware',

]

ROOT_URLCONF = 'config.urls'
PUBLIC_SCHEMA_URLCONF = 'config.public_urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.security.context_processors.site_settings'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

def get_db_config(environ_var='DATABASE_URL'):
    """Get Database configuration."""
    options = env.db(var=environ_var, default='sqlite:///db.sqlite3')
    if options.get('ENGINE') != 'django.db.backends.sqlite3':
        return options

    # This will allow use a relative to the project root DB path
    # for SQLite like 'sqlite:///db.sqlite3'
    if not options['NAME'] == ':memory:' and not os.path.isabs(options['NAME']):
        options.update({'NAME': os.path.join(BASE_DIR, options['NAME'])})

    return options


db_config = get_db_config()
db_config['ENGINE'] = 'django_tenants.postgresql_backend'

DATABASES = {
    'default': db_config,
    'mongo_db': {
        'ENGINE': 'djongo',
        'NAME': env('DB_MONGO_NAME'),
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': env('DB_MONGO_HOST'),
            'port': env.int('DB_MONGO_PORT', default=27017),
            'username': env('DB_MONGO_USERNAME'),
            'password': env('DB_MONGO_PASSWORD'),
            'authSource': env('DB_MONGO_NAME'),
            'authMechanism': 'SCRAM-SHA-1'
        },
        'LOGGING': {
            'version': 1,
            'loggers': {
                'djongo': {
                    'level': 'DEBUG',
                    'propagate': False,
                }
            },
        },
    }
}

DATABASE_ROUTERS = [
    'django_tenants.routers.TenantSyncRouter',
    'core.network.utils.db_routers.Router',
]

# Django-tenant-schemas

TENANT_MODEL = 'multicpy.Scheme'

TENANT_DOMAIN_MODEL = 'multicpy.Domain'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'
USE_TZ = True

USE_I18N = True


USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


MEDIA_URL = '/media/'

# Auth

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/'

AUTH_USER_MODEL = 'users.Usuario'

# Email

EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')


# Sessions

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

SESSION_COOKIE_NAME = 'huaweioltconnect'

SESSION_COOKIE_AGE = 60 * 240

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# HTTP

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# rest_framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # global exception handler ---
    'EXCEPTION_HANDLER': 'config.shared.helpers.handle_rest_exception_drf_helper.handle_rest_exception_drf_helper',

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        #'rest_framework_xml.renderers.XMLRenderer'
    ]
}

# Django-cacheops

# ### Cache
CACHES = {
    "default": {
        # "BACKEND": "django_redis.cache.RedisCache",
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get('REDIS_URL'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# CACHEOPS_REDIS = {
#     'host': env.str('REDIS_HOST', default='localhost'),
#     'port': 6379,
#     'db': 1,
#     'socket_timeout': 3,
# }

# CACHEOPS = {
#     '*.*': {'ops': (), 'timeout': 0},
#     'billing.customer': {'ops': 'all', 'timeout': 60 * 15},
#     'billing.contract': {'ops': 'all', 'timeout': 60 * 15},
#     'network.ontcontract': {'ops': 'all', 'timeout': 60 * 15},
#     'network.route': {'ops': 'all', 'timeout': 60 * 15},
#     'network.boxroute': {'ops': 'all', 'timeout': 60 * 15},
# }

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Constants

CUSTOMER_GROUP = 2

DOMAIN = env.str('DOMAIN', default='localhost')

DEFAULT_SCHEMA = env.str('DEFAULT_SCHEMA', default='public')


# ### ### ### =================================================

# ### Swagger
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'SECURITY_REQUIREMENTS': [
        {
            'Token': []
        }
    ],
}


# ### CORS Origin ===========================
CORS_ALLOW_HEADERS = list(default_headers) + ['x-front-version']
CORS_ALLOWED_ORIGINS = env.str('CORS_ALLOWED_ORIGINS').split(',')
# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.31.212:5175",
#     "http://localhost:5175",
# ]
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')
# ALLOWED_HOSTS = [
#     "127.0.0.1",
#     "localhost",
#     "192.168.31.212",
# ]


CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ["*"]


# ### ### ### =================================================
# ### Constants Envs -------------
BLOCK_SOLSERVICIO_HOURS = env.int('BLOCK_SOLSERVICIO_HOURS', default=48)
API_MICRO_CONSULTA_CEDULARUCEQUIFAX_URL = env.str(
    'API_MICRO_CONSULTA_CEDULARUCEQUIFAX_URL')
MIKRO_TOKEN = env.str('MIKRO_TOKEN')
MIKRO_CLIENTES_URL = env.str('MIKRO_CLIENTES_URL')

SECRET_KEY_S360_OFIVIRTUAL= env.str('SECRET_KEY_S360_OFIVIRTUAL', default='')

IS_PROD = env.str('STAGE') == 'prod'
SEND_EMAILS = env.bool('SEND_EMAILS', default=False)

# consultas visitaecuador
API_CONSULTA_IDENTIFICACION_URL = env.str('API_CONSULTA_IDENTIFICACION_URL')
API_CONSULTA_IDENTIFICACION_ID = env.str('API_CONSULTA_IDENTIFICACION_ID')
API_CONSULTA_IDENTIFICACION_PASS = env.str(
    'API_CONSULTA_IDENTIFICACION_PASS')
API_CONSULTA_IDENTIFICACION_ID_SERVICIO = env.str(
    'API_CONSULTA_IDENTIFICACION_ID_SERVICIO')
API_CONSULTA_IDENTIFICACION_CANAL = env.str(
    'API_CONSULTA_IDENTIFICACION_CANAL')

# ofi virtual
API_OFIVIRTUAL_BASE_URL = env.str('API_OFIVIRTUAL_BASE_URL')
API_OFIVIRTUAL_USERNAME = env.str('API_OFIVIRTUAL_USERNAME')
API_OFIVIRTUAL_PASSWORD = env.str('API_OFIVIRTUAL_PASSWORD')
API_OFIVIRTUAL_AUHT_TOKEN = env.str('API_OFIVIRTUAL_AUHT_TOKEN')



# abitmedia
ABITMEDIA_BASE_URL = env.str('ABITMEDIA_BASE_URL')
ABITMEDIA_TOKEN = env.str('ABITMEDIA_TOKEN')


# Switch
SWITCH_API_URL = env.str('SWITCH_API_URL')
SWITCH_API_AUTH_CLIENT_ID = env.str('SWITCH_API_AUTH_CLIENT_ID')
SWITCH_API_AUTH_CLIENT_SECRET = env.str('SWITCH_API_AUTH_CLIENT_SECRET')


# CRONJOBS = [
#     # ('0 * * * *', 'core.cron.cron_test_ten', '>> /var/log/cron.log 2>&1'),
#     # ('* * * * *', 'core.cron.cron_1', '>> /var/log/cron.log 2>&1'),
#     ('* * * * *', 'core.cron.cron_1.cron_1',
#      '>> /workspaces/python/code/a_synergia/01_erp/01_huaweiolt/cron_1.log 2>&1'),
#     # ('0 * * * *', 'core.cron.cron_2', '>> /var/log/cron.log 2>&1'),
#     # ('0 * * * *', 'core.cron.cron_rubros', '>> /var/log/cron.log 2>&1'),
#     # ('0 * * * *', 'core.cron.cron_config', '>> /var/log/cron.log 2>&1'),
#     # ('0 * * * *', 'core.cron.cron_bloqueos', '>> /var/log/cron.log 2>&1'),
# ]


# #### CELERY =================================
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'America/Guayaquil'  # explícito

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='amqp://guest:guest@rabbitmq:5672//')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# ==== Elasticsearch ====
ES_URL = env.str("ES_URL_ES", "http://localhost:9200")
ES_USER = env.str("ES_USER", default=None)
ES_PASS = env.str("ES_PASS", default=None)
ES_INDEX_PREFIX = env.str("ES_INDEX_PREFIX", "audit")
ES_INDEX_ROLLOVER = env.str("ES_INDEX_ROLLOVER", "monthly")  # daily|monthly

# ==== Celery tuning para logs ====
# CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# CELERY_TASK_ACKS_LATE = True


# -------------
BIN_VALIDATOR_API_URL = env.str('BIN_VALIDATOR_API_URL', default='')
BIN_VALIDATOR_API_KEY = env.str('BIN_VALIDATOR_API_KEY', default='')




# Al final de settings.py, justo tras CELERY_*
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "loggers": {
#         # Logger raíz para tu app y Celery
#         "": {
#             "handlers": ["console"],
#             "level": "INFO",
#             "propagate": True,
#         },
#         # Silenciar el detalle de WeasyPrint
#         "weasyprint": {
#             "handlers": ["console"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         # Silenciar el detalle de fontTools
#         "fontTools.subset": {
#             "handlers": ["console"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         # Opcional: otros parsers CSS muy verbosos
#         "cssselect.parser": {
#             "handlers": ["console"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#     },
# }




# ### MONITORING ----------------------------------
# 1) Añade django-prometheus
INSTALLED_APPS.insert(0, 'django_prometheus')

# 2) Middleware de métricas
MIDDLEWARE.insert(0, 'django_prometheus.middleware.PrometheusBeforeMiddleware')
MIDDLEWARE.append('django_prometheus.middleware.PrometheusAfterMiddleware')



# ### 2FA -----------------------------------
# redis ------
MFA_CHALLENGE_TTL_SECONDS = env.int('MFA_CHALLENGE_TTL_SECONDS', default=300)  # 5 min
MFA_CHALLENGE_NS = env.str('MFA_CHALLENGE_NS', default='erp:prod:mfa:challenge')



# ### CRM -------------------------------
EXTERNAL_CRM_API_BASE_URL = env.str('EXTERNAL_CRM_API_BASE_URL')
EXTERNAL_CRM_USERNAME = env.str('EXTERNAL_CRM_USERNAME')
EXTERNAL_CRM_PASSWORD = env.str('EXTERNAL_CRM_PASSWORD')


# 4) Logging estructurado JSON para Promtail
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
        'standard': {
            'format': '[%(asctime)s | %(levelname)s] %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
